apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-registry-config
  namespace: kube-ops
data:
  config: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /storage
      cache:
        layerinfo: inmemory
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
    http:
      addr: :5000
      secret: placeholder
      debug:
        addr: localhost:5001
    auth:
      token:
        issuer: registry-token-issuer
        realm: http://reg.mydomain.com/service/token
        rootcertbundle: /etc/docker/registry/root.crt
        service: token-service
    notifications:
      endpoints:
        - name: harbor
          disabled: false
          url: http://ui/service/notifications
          timeout: 3000ms
          threshold: 5
          backoff: 1s

  cert: |


